# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_policy.c24aacc7ec26455cbc6a0976b8e00ce0-policy:
resource "aws_iam_policy" "c24aacc7ec26455cbc6a0976b8e00ce0-policy" {
  description = "Team Policy"
  name        = "c24aacc7ec26455cbc6a0976b8e00ce0-policy"
  path        = "/"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "cloud9:*",
            "lambda:*",
            "ecr:*",
            "codebuild:*",
            "cloudformation:*",
            "cloudwatch:*",
            "ec2:*",
            "elasticloadbalancing:*",
            "eks:*",
            "ecs:*",
            "logs:*",
            "s3:*",
            "ssm:*",
            "dynamodb:*",
            "iam:*",
            "autoscaling:*",
            "appmesh:*",
            "xray:*",
            "sns:*",
            "codepipeline:*",
          ]
          Effect     = "Allow"
          "Resource" = "*"
          Sid        = "Allow"
        },
        {
          Action = [
            "iam:*AccessKey",
            "iam:*User*",
            "iam:*User",
            "ec2:Purchase*",
            "ec2:*CapacityReservation",
          ]
          Effect     = "Deny"
          "Resource" = "*"
          Sid        = "Deny"
        },
      ]
      Version = "2012-10-17"
    }
  )
  tags     = {}
  tags_all = {}
}
