# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-0ff36daf7e7628844:
resource "aws_subnet" "subnet-0ff36daf7e7628844" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1c"
  cidr_block                      = "172.31.16.0/20"
  map_public_ip_on_launch         = true
  tags                            = {}
  tags_all                        = {}
  vpc_id                          = aws_vpc.vpc-0ef9c60aaf76a3fc6.id

  timeouts {}
}
