# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb_target_group.arn_aws_elasticloadbalancing_eu-west-1_479455118968_targetgroup_mod-c-Mythi-1FH7EXGEU82CO_5ce99e3459c42fb4:
resource "aws_lb_target_group" "arn_aws_elasticloadbalancing_eu-west-1_479455118968_targetgroup_mod-c-Mythi-1FH7EXGEU82CO_5ce99e3459c42fb4" {
  deregistration_delay          = "300"
  load_balancing_algorithm_type = "round_robin"
  name                          = "mod-c-Mythi-1FH7EXGEU82CO"
  port                          = 80
  protocol                      = "HTTP"
  protocol_version              = "HTTP1"
  slow_start                    = 0
  tags                          = {}
  tags_all                      = {}
  target_type                   = "ip"
  vpc_id                        = aws_vpc.vpc-0a81be22c25965108.id

  health_check {
    enabled             = true
    healthy_threshold   = 3
    interval            = 10
    matcher             = "200"
    path                = "/"
    port                = "traffic-port"
    protocol            = "HTTP"
    timeout             = 5
    unhealthy_threshold = 3
  }

  stickiness {
    cookie_duration = 86400
    enabled         = false
    type            = "lb_cookie"
  }
}
