# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.mod-c24aacc7ec26455c-EcsServiceRole-DV5IQXOF68PL__ecs-service:
resource "aws_iam_role_policy" "mod-c24aacc7ec26455c-EcsServiceRole-DV5IQXOF68PL__ecs-service" {
  name = "ecs-service"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "ec2:AttachNetworkInterface",
            "ec2:CreateNetworkInterface",
            "ec2:CreateNetworkInterfacePermission",
            "ec2:DeleteNetworkInterface",
            "ec2:DeleteNetworkInterfacePermission",
            "ec2:Describe*",
            "ec2:DetachNetworkInterface",
            "elasticloadbalancing:DeregisterInstancesFromLoadBalancer",
            "elasticloadbalancing:DeregisterTargets",
            "elasticloadbalancing:Describe*",
            "elasticloadbalancing:RegisterInstancesWithLoadBalancer",
            "elasticloadbalancing:RegisterTargets",
            "iam:PassRole",
            "ecr:GetAuthorizationToken",
            "ecr:BatchCheckLayerAvailability",
            "ecr:GetDownloadUrlForLayer",
            "ecr:BatchGetImage",
            "logs:DescribeLogStreams",
            "logs:CreateLogStream",
            "logs:CreateLogGroup",
            "logs:PutLogEvents",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
      ]
    }
  )
  role = aws_iam_role.mod-c24aacc7ec26455c-EcsServiceRole-DV5IQXOF68PL.id
}
