# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-0dbd59ab370f60086:
resource "aws_subnet" "subnet-0dbd59ab370f60086" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1b"
  cidr_block                      = "10.0.3.0/24"
  map_public_ip_on_launch         = false
  tags = {
    "Name" = "MysfitsPrivateTwo-mod-c24aacc7ec26455c"
  }
  tags_all = {
    "Name" = "MysfitsPrivateTwo-mod-c24aacc7ec26455c"
  }
  vpc_id = aws_vpc.vpc-0a81be22c25965108.id

  timeouts {}
}
