# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-0e86da4cf4e81df07:
resource "aws_nat_gateway" "nat-0e86da4cf4e81df07" {
  allocation_id     = aws_eip.eipalloc-05695dd50cb5c2498.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-087318f7306293146.id
  tags              = {}
  tags_all          = {}
}
