# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0b851d3810e0db083:
resource "aws_security_group" "sg-0b851d3810e0db083" {
  description = "Access to the fargate containers from the Internet"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.vpc-0a81be22c25965108.id

  timeouts {}
}
