# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb_listener.arn_aws_elasticloadbalancing_eu-west-1_479455118968_listener_app_alb-mod-c24aacc7ec26455c_6bbeece1171d6b81_aade53e811aba12e:
resource "aws_lb_listener" "arn_aws_elasticloadbalancing_eu-west-1_479455118968_listener_app_alb-mod-c24aacc7ec26455c_6bbeece1171d6b81_aade53e811aba12e" {
  load_balancer_arn = aws_lb.arn_aws_elasticloadbalancing_eu-west-1_479455118968_loadbalancer_app_alb-mod-c24aacc7ec26455c_6bbeece1171d6b81.arn
  port              = 80
  protocol          = "HTTP"
  tags              = {}
  tags_all          = {}

  default_action {
    target_group_arn = aws_lb_target_group.arn_aws_elasticloadbalancing_eu-west-1_479455118968_targetgroup_mod-c-Mythi-1FH7EXGEU82CO_5ce99e3459c42fb4.arn
    type             = "forward"
  }

  timeouts {}
}
