# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_cloudwatch_log_group.mod-c24aacc7ec26455c-MythicalMonolithLogGroup-A9DqmJvGeCqt:
resource "aws_cloudwatch_log_group" "mod-c24aacc7ec26455c-MythicalMonolithLogGroup-A9DqmJvGeCqt" {
  name              = "mod-c24aacc7ec26455c-MythicalMonolithLogGroup-A9DqmJvGeCqt"
  retention_in_days = 0
  tags              = {}
  tags_all          = {}
}
