# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0fc5cc8db2ea5d68b_ingress_1:
resource "aws_security_group_rule" "sg-0fc5cc8db2ea5d68b_ingress_1" {
  from_port         = 0
  prefix_list_ids   = []
  protocol          = "-1"
  security_group_id = data.aws_security_group.sg-0fc5cc8db2ea5d68b.id
  self              = true
  to_port           = 0
  type              = "ingress"
}
