# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-095a1c69b67e1d58f:
resource "aws_subnet" "subnet-095a1c69b67e1d58f" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1b"
  cidr_block                      = "172.31.0.0/20"
  map_public_ip_on_launch         = true
  tags                            = {}
  tags_all                        = {}
  vpc_id                          = aws_vpc.vpc-0ef9c60aaf76a3fc6.id

  timeouts {}
}
