# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy_attachment.TeamRole__c24aacc7ec26455cbc6a0976b8e00ce0-policy:
resource "aws_iam_role_policy_attachment" "TeamRole__c24aacc7ec26455cbc6a0976b8e00ce0-policy" {
  policy_arn = aws_iam_policy.c24aacc7ec26455cbc6a0976b8e00ce0-policy.arn
  role       = aws_iam_role.TeamRole.id
}
