# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket.mod-c24aacc7ec26455c-mythicalbucket-1dzr22hp2tt9w:
resource "aws_s3_bucket" "mod-c24aacc7ec26455c-mythicalbucket-1dzr22hp2tt9w" {
  bucket = "mod-c24aacc7ec26455c-mythicalbucket-1dzr22hp2tt9w"
  lifecycle {
    ignore_changes = [acl, force_destroy]
  }
  request_payer    = "BucketOwner"
  tags             = {}
  tags_all         = {}

  grant {
    permissions = [
      "READ",
    ]
    type = "Group"
    uri  = "http://acs.amazonaws.com/groups/global/AllUsers"
  }
  grant {
    id = "06ebb6c716efa9893e0d611c9afffaae4e73bed6b2b38eac1b732e66e212b15e"
    permissions = [
      "FULL_CONTROL",
    ]
    type = "CanonicalUser"
  }

  versioning {
    enabled    = false
    mfa_delete = false
  }

  website {
    error_document = "error.html"
    index_document = "index.html"
  }
  force_destroy = false
}
