# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-0589b0b80cee26569:
resource "aws_security_group" "sg-0589b0b80cee26569" {
  description = "Access to the load balancer"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.vpc-0a81be22c25965108.id

  timeouts {}
}
