# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-04878d7caa7527a55_ingress_1:
resource "aws_security_group_rule" "sg-04878d7caa7527a55_ingress_1" {
  cidr_blocks = [
    "81.96.210.11/32",
  ]
  from_port         = 22
  prefix_list_ids   = []
  protocol          = "tcp"
  security_group_id = aws_security_group.sg-04878d7caa7527a55.id
  to_port           = 22
  type              = "ingress"
}
