# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role_policy.mod-c24aacc7ec26455c-ECSTaskRole-22OPM1OFJ77W__AmazonECSTaskRolePolicy:
resource "aws_iam_role_policy" "mod-c24aacc7ec26455c-ECSTaskRole-22OPM1OFJ77W__AmazonECSTaskRolePolicy" {
  name = "AmazonECSTaskRolePolicy"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "ecr:GetAuthorizationToken",
            "ecr:BatchCheckLayerAvailability",
            "ecr:GetDownloadUrlForLayer",
            "ecr:BatchGetImage",
            "logs:CreateLogStream",
            "logs:CreateLogGroup",
            "logs:PutLogEvents",
          ]
          Effect   = "Allow"
          Resource = "*"
        },
        {
          Action = [
            "dynamodb:Scan",
            "dynamodb:Query",
            "dynamodb:UpdateItem",
            "dynamodb:GetItem",
          ]
          Effect   = "Allow"
          Resource = "arn:aws:dynamodb:eu-west-1:479455118968:table/containersidc24aacc7ec26455c"
        },
      ]
    }
  )
  role = aws_iam_role.mod-c24aacc7ec26455c-ECSTaskRole-22OPM1OFJ77W.id
}
