# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0ee8cf391aea8902c__rtbassoc-03c0b3fd0418e1532:
resource "aws_route_table_association" "subnet-0ee8cf391aea8902c__rtbassoc-03c0b3fd0418e1532" {
  route_table_id = aws_route_table.rtb-0c326cbb7444a14f7.id
  subnet_id      = aws_subnet.subnet-0ee8cf391aea8902c.id
}
