# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb.arn_aws_elasticloadbalancing_eu-west-1_479455118968_loadbalancer_app_alb-mod-c24aacc7ec26455c_6bbeece1171d6b81:
resource "aws_lb" "arn_aws_elasticloadbalancing_eu-west-1_479455118968_loadbalancer_app_alb-mod-c24aacc7ec26455c_6bbeece1171d6b81" {
  #"arn:aws:elasticloadbalancing:eu-west-1:479455118968:loadbalancer/app/alb-mod-c24aacc7ec26455c/6bbeece1171d6b81"
  desync_mitigation_mode     = "defensive"
  drop_invalid_header_fields = false
  enable_deletion_protection = false
  enable_http2               = true
  enable_waf_fail_open       = false
  idle_timeout               = 60
  internal                   = false
  ip_address_type            = "ipv4"
  load_balancer_type         = "application"
  name                       = "alb-mod-c24aacc7ec26455c"
  security_groups = [
    aws_security_group.sg-0589b0b80cee26569.id,
  ]
  subnets = [
    aws_subnet.subnet-087318f7306293146.id,
    aws_subnet.subnet-0ee8cf391aea8902c.id,
  ]
  tags     = {}
  tags_all = {}

  access_logs {
    bucket  = ""
    enabled = false
  }

  subnet_mapping {
    subnet_id = aws_subnet.subnet-087318f7306293146.id
  }
  subnet_mapping {
    subnet_id = aws_subnet.subnet-0ee8cf391aea8902c.id
  }

  timeouts {}
}
