# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0b851d3810e0db083_ingress_1:
resource "aws_security_group_rule" "sg-0b851d3810e0db083_ingress_1" {
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  from_port         = 0
  prefix_list_ids   = []
  protocol          = "-1"
  security_group_id = aws_security_group.sg-0b851d3810e0db083.id
  to_port           = 0
  type              = "ingress"
}
