# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_instance_profile.mod-c24aacc7ec26455c-MythicalProfile-F47YWRZMZK1P:
resource "aws_iam_instance_profile" "mod-c24aacc7ec26455c-MythicalProfile-F47YWRZMZK1P" {
  name     = "mod-c24aacc7ec26455c-MythicalProfile-F47YWRZMZK1P"
  path     = "/"
  role     = aws_iam_role.TeamRole.name
  tags     = {}
  tags_all = {}
}
