# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_ecs_cluster.Cluster-mod-c24aacc7ec26455c:
resource "aws_ecs_cluster" "Cluster-mod-c24aacc7ec26455c" {
#  capacity_providers = []
  name               = "Cluster-mod-c24aacc7ec26455c"
  tags               = {}
  tags_all           = {}

  setting {
    name  = "containerInsights"
    value = "disabled"
  }
}
