# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.subnet-087318f7306293146:
resource "aws_subnet" "subnet-087318f7306293146" {
  assign_ipv6_address_on_creation = false
  availability_zone               = "eu-west-1a"
  cidr_block                      = "10.0.0.0/24"
  map_public_ip_on_launch         = true
  tags = {
    "Name" = "MysfitsPublicOne-mod-c24aacc7ec26455c"
  }
  tags_all = {
    "Name" = "MysfitsPublicOne-mod-c24aacc7ec26455c"
  }
  vpc_id = aws_vpc.vpc-0a81be22c25965108.id

  timeouts {}
}
