# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-05a205b33c62494bb:
resource "aws_nat_gateway" "nat-05a205b33c62494bb" {
  allocation_id     = aws_eip.eipalloc-0257f1bca423bd7dd.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.subnet-0ee8cf391aea8902c.id
  tags              = {}
  tags_all          = {}
}
