# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_dynamodb_table.containersidc24aacc7ec26455c:
resource "aws_dynamodb_table" "containersidc24aacc7ec26455c" {
  lifecycle {
    ignore_changes = [ttl[0].attribute_name, read_capacity, write_capacity]
  }
  billing_mode   = "PROVISIONED"
  hash_key       = "MysfitId"
  name           = "containersidc24aacc7ec26455c"
  read_capacity  = 5
  stream_enabled = false
  tags           = {}
  tags_all       = {}
  write_capacity = 5

  attribute {
    name = "GoodEvil"
    type = "S"
  }
  attribute {
    name = "LawChaos"
    type = "S"
  }
  attribute {
    name = "MysfitId"
    type = "S"
  }

  global_secondary_index {
    hash_key           = "GoodEvil"
    name               = "GoodEvilIndex"
    non_key_attributes = []
    projection_type    = "ALL"
    range_key          = "MysfitId"
    read_capacity      = 5
    write_capacity     = 5
  }
  global_secondary_index {
    hash_key           = "LawChaos"
    name               = "LawChaosIndex"
    non_key_attributes = []
    projection_type    = "ALL"
    range_key          = "MysfitId"
    read_capacity      = 5
    write_capacity     = 5
  }

  point_in_time_recovery {
    enabled = false
  }

  timeouts {}

  ttl {
    attribute_name = "TimeToExist"
    enabled        = false
  }
}
