# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_eip.eipalloc-05695dd50cb5c2498:
resource "aws_eip" "eipalloc-05695dd50cb5c2498" {
  network_border_group = "eu-west-1"
  public_ipv4_pool     = "amazon"
  tags                 = {}
  tags_all             = {}
  vpc                  = true

  timeouts {}
}
