# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group_rule.sg-0589b0b80cee26569_ingress_1:
resource "aws_security_group_rule" "sg-0589b0b80cee26569_ingress_1" {
  cidr_blocks = [
    "0.0.0.0/0",
  ]
  from_port         = 80
  prefix_list_ids   = []
  protocol          = "tcp"
  security_group_id = aws_security_group.sg-0589b0b80cee26569.id
  to_port           = 80
  type              = "ingress"
}
